# Site settings
title: ddkto
email: david@dekoning.ca
description: "ddkto's thoughts"
baseurl: ""
url: "http://david.dekoning.ca"
twitter_username: ddkto
github_username:  daviddekoning

# Build settings
name: ddkto
highlighter: rouge
permalink: pretty
incremental: true